/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionSummaryDTO } from './sessionSummaryDTO';
import { VehicleSummaryDTO } from './vehicleSummaryDTO';
import { TraineeSummaryDTO } from './traineeSummaryDTO';
import { ProfileDTO } from './profileDTO';


export interface InstructorDetailsDTO { 
    readonly uuid?: string;
    profile: ProfileDTO;
    readonly vehicles?: Set<VehicleSummaryDTO>;
    readonly trainees?: Set<TraineeSummaryDTO>;
    readonly sessions?: Set<SessionSummaryDTO>;
}

