/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileDTO { 
    readonly uuid?: string;
    name: string;
    phoneNumber: string;
    address?: string;
    imageUrl?: string;
}

