/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleSummaryDTO } from './vehicleSummaryDTO';
import { InstructorSummaryDTO } from './instructorSummaryDTO';
import { TraineeSummaryDTO } from './traineeSummaryDTO';


export interface SessionDetailsDTO { 
    uuid?: string;
    scheduledAt?: string;
    trainee?: TraineeSummaryDTO;
    instructor?: InstructorSummaryDTO;
    vehicle?: VehicleSummaryDTO;
}

