/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SessionSummaryDTO { 
    uuid?: string;
    scheduledAt?: string;
    traineeName?: string;
    instructorName?: string;
    vehicleOutline?: string;
}

