/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileDTO } from './profileDTO';


export interface TraineeSummaryDTO { 
    uuid: string;
    profile: ProfileDTO;
}

