/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionSummaryDTO } from './sessionSummaryDTO';
import { VehicleSummaryDTO } from './vehicleSummaryDTO';
import { InstructorSummaryDTO } from './instructorSummaryDTO';
import { ProfileDTO } from './profileDTO';


export interface TraineeDetailsDTO { 
    readonly uuid?: string;
    profile: ProfileDTO;
    readonly instructor?: InstructorSummaryDTO;
    readonly vehicle?: VehicleSummaryDTO;
    readonly sessions?: Set<SessionSummaryDTO>;
}

