/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileDTO } from './profileDTO';


export interface UserDetailsDTO { 
    uuid?: string;
    profile?: ProfileDTO;
    username?: string;
    role?: string;
}

