/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehicleSummaryDTO { 
    uuid: string;
    model: string;
    make: string;
    year: string;
    transmissionType: VehicleSummaryDTOTransmissionTypeEnum;
    engineType: VehicleSummaryDTOEngineTypeEnum;
    imageUrl?: string;
}
export enum VehicleSummaryDTOTransmissionTypeEnum {
    AUTOMATIC = 10,
    MANUAL = 20
};
export enum VehicleSummaryDTOEngineTypeEnum {
    INTERNAL_COMBUSTION = 10,
    HYBRID = 20,
    ELECTRIC = 30
};



