/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionSummaryDTO } from './sessionSummaryDTO';
import { InstructorSummaryDTO } from './instructorSummaryDTO';
import { TraineeSummaryDTO } from './traineeSummaryDTO';


export interface VehicleDetailsDTO { 
    readonly uuid?: string;
    model: string;
    make: string;
    year: string;
    licensePlate: string;
    color: string;
    engineType: VehicleDetailsDTOEngineTypeEnum;
    fuelType: VehicleDetailsDTOFuelTypeEnum;
    transmissionType: VehicleDetailsDTOTransmissionTypeEnum;
    imageUrl?: string;
    readonly instructors?: Set<InstructorSummaryDTO>;
    readonly trainees?: Set<TraineeSummaryDTO>;
    readonly sessions?: Set<SessionSummaryDTO>;
}
export enum VehicleDetailsDTOEngineTypeEnum {
    INTERNAL_COMBUSTION = 10,
    HYBRID = 20,
    ELECTRIC = 30
};
export enum VehicleDetailsDTOFuelTypeEnum {
    GASOLINE = 10,
    DIESEL = 20,
    ELECTRIC = 30
};
export enum VehicleDetailsDTOTransmissionTypeEnum {
    AUTOMATIC = 10,
    MANUAL = 20
};



